baseURL = 'https://blog-lx5.pages.dev/'
languageCode = 'en-us'
title = 'myblog'
theme = "anatole"


[params]
  title = "hello kitty"
  author = "zhengxin"
  description = "zhengxinqinaxing"
  profilePicture = "images/profile.jpg"